apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: assignment3
type: Opaque
data:
  mysql_root_password: cm9vdHBhc3M=    # base64 for "rootpass"
  mysql_user: Zmxhc2t1c2Vy            # base64 for "flaskuser"
  mysql_password: Zmxhc2twYXNz        # base64 for "flaskpass"
  mysql_database: Zmxhc2tkYg==        # base64 for "flaskdb"
